# Use the official Debian base image
FROM ubuntu:jammy

RUN apt update && apt upgrade -y

RUN apt install -y --no-install-recommends \
ca-certificates \
build-essential \
wget \
vim


# Define the command to run your application
# CMD ["./your_app_executable"]
