return {}
-- return {
--     "neovim/nvim-lspconfig",
--     dependencies = {
--         "saghen/blink.cmp",
--         {
--             "folke/lazydev.nvim",
--             opts = {
--                 library = {
--                     { path = "${3rd}/luv/library", words = { "vim%.uv" } },
--                 },
--             },
--         },
--     },

--     opts = {
--         servers = {
--             gopls = {},
--             groovyls = {
--                 cmd = { "groovy-language-server" },
--             },
--             bashls = {},
--             ts_ls = {},
--             ruff = {},
--             lua_ls = {
--                 settings = {
--                     diagnostics = {
--                         globals = { "vim" },
--                     },
--                 },
--             },
--             zls = {},
--             jsonls = {},
--             clangd = {},
--             yamlls = {},
--             -- lemminx = {
--             --     settings = {
--             --         format = {
--             --             insertSpaces = true,
--             --             tabSize = 4,
--             --         },
--             --     },
--             -- },
--             rust_analyzer = {
--                 imports = {
--                     granularity = {
--                         group = "module",
--                     },
--                     prefix = "self",
--                 },
--                 cargo = {
--                     buildScripts = {
--                         enable = false,
--                     },
--                 },
--                 procMacro = {
--                     enable = false,
--                 },
--             },
--             pyright = {
--                 {
--                     -- Using Ruff's import organizer
--                     disableOrganizeImports = true,
--                 },
--                 python = {
--                     analysis = {
--                         -- Ignore all files for analysis to exclusively use Ruff for linting
--                         ignore = { "*" },
--                     },
--                 },
--             },
--         },
--     },
--     config = function(_, opts)
--         local lspconfig = require("lspconfig")
--         for server, config in pairs(opts.servers) do
--             config.capabilities = require("blink.cmp").get_lsp_capabilities(config.capabilities)
--             lspconfig[server].setup(config)
--         end
--     end,
-- }
